# -*- coding: utf-8 -*-
"""Copy of Exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dP023DymRSR8_5mmPDqg8bTMGRvsj3FX

# Dataset Descriptions

## 1. Iris Dataset

### Description
The Iris dataset is one of the most popular datasets in machine learning. It contains measurements of iris flowers from three different species: Setosa, Versicolor, and Virginica. The objective is to classify each flower into its correct species based on four flower measurements.

### Features
- Sepal Length (cm)
- Sepal Width (cm)
- Petal Length (cm)
- Petal Width (cm)

### Target Classes
- Setosa
- Versicolor
- Virginica

### Dataset Summary
- Number of Samples: **150**
- Number of Features: **4**
- Number of Classes: **3**
- Task: **Multiclass Classification**
- Missing Values: **None**

---

## 2. Sonar Dataset

### Description
The Sonar dataset is used for binary classification. It contains sonar signals reflected from either rocks or metal cylinders (mines). Each instance consists of 60 numerical attributes representing the energy of sonar signals at different frequencies. The goal is to determine whether the object is a rock or a mine.

### Features
- 60 numerical attributes representing sonar signal energy at different frequencies.

### Target Classes
- R (Rock)
- M (Mine)

### Dataset Summary
- Number of Samples: **208**
- Number of Features: **60**
- Number of Classes: **2**
- Task: **Binary Classification**
- Missing Values: **None**

---

## 3. Pima Indians Diabetes Dataset

### Description
The Pima Indians Diabetes dataset is a medical dataset used to predict whether a patient has diabetes based on diagnostic measurements. The dataset includes health-related information collected from adult female patients.

### Features
- Pregnancies
- Glucose
- Blood Pressure
- Skin Thickness
- Insulin
- Body Mass Index (BMI)
- Diabetes Pedigree Function
- Age

### Target Classes
- 0 : No Diabetes
- 1 : Diabetes

### Dataset Summary
- Number of Samples: **768**
- Number of Features: **8**
- Number of Classes: **2**
- Task: **Binary Classification**
- Missing Values: Some features contain zero values that are commonly treated as missing during preprocessing.

---

## Comparison of Datasets

| Dataset | Samples | Features | Classes | Task |
|----------|---------|----------|---------|------|
| Iris | 150 | 4 | 3 | Multiclass Classification |
| Sonar | 208 | 60 | 2 | Binary Classification |
| Pima Indians Diabetes | 768 | 8 | 2 | Binary Classification |

## Task 1: Loading of Dataset and NumPy, Pandas Basics for Data Exploration
"""

import numpy as np

np.version.version

import numpy as np

    # ===========================
    # Creating Arrays
    # ===========================

    arr1 = np.array([10, 20, 30, 40, 50])
    print("1D Array:", arr1)

    arr2 = np.array([[1, 2, 3],
                     [4, 5, 6]])
    print("\n2D Array:\n", arr2)

    # ===========================
    # Special Arrays
    # ===========================

    print("\nZeros Array:")
    print(np.zeros((2, 3)))

    print("\nOnes Array:")
    print(np.ones((3, 3)))

    print("\nIdentity Matrix:")
    print(np.eye(4))

    print("\nArray with Range:")
    print(np.arange(1, 11))

    print("\nEven Numbers:")
    print(np.arange(2, 21, 2))

    print("\nLinearly Spaced Values:")
    print(np.linspace(0, 10, 5))

    # ===========================
    # Array Properties
    # ===========================

    print("\nShape:", arr2.shape)
    print("Size:", arr2.size)
    print("Dimensions:", arr2.ndim)
    print("Data Type:", arr2.dtype)

    # ===========================
    # Mathematical Operations
    # ===========================

    print("\nAddition:", arr1 + 5)
    print("Subtraction:", arr1 - 5)
    print("Multiplication:", arr1 * 2)
    print("Division:", arr1 / 2)
    print("Square:", arr1 ** 2)
    print("Square Root:", np.sqrt(arr1))

    # ===========================
    # Statistical Functions
    # ===========================

    print("\nSum:", np.sum(arr1))
    print("Mean:", np.mean(arr1))
    print("Median:", np.median(arr1))
    print("Maximum:", np.max(arr1))
    print("Minimum:", np.min(arr1))
    print("Standard Deviation:", np.std(arr1))
    print("Variance:", np.var(arr1))

# ===========================
# Indexing and Slicing
# ===========================

print("\nFirst Element:", arr1[0])
print("Last Element:", arr1[-1])
print("Elements from Index 1 to 3:", arr1[1:4])

# ===========================
# Reshaping Arrays
# ===========================

a = np.arange(1, 13)
print("\nOriginal Array:")
print(a)

print("\nReshaped to 3x4:")
print(a.reshape(3, 4))

# ===========================
# Array Concatenation
# ===========================

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nConcatenated Array:")
print(np.concatenate((a, b)))

# ===========================
# Sorting
# ===========================

arr = np.array([8, 3, 9, 1, 5])

print("\nOriginal:", arr)
print("Sorted:", np.sort(arr))

# ===========================
# Random Numbers
# ===========================

print("\nRandom Integers:")
print(np.random.randint(1, 100, 5))

print("\nRandom Decimal Numbers:")
print(np.random.rand(3))

# ===========================
# Matrix Operations
# ===========================

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("\nMatrix Addition:")
print(A + B)

print("\nMatrix Subtraction:")
print(A - B)

print("\nMatrix Multiplication:")
print(np.dot(A, B))

print("\nTranspose of Matrix A:")
print(A.T)

# ===========================
# Logical Operations
# ===========================

print("\nElements Greater Than 25:")
print(arr1 > 25)

print("\nElements Greater Than 25:")
print(arr1[arr1 > 25])

# ===========================
# Aggregate Operations
# ===========================

matrix = np.array([[2, 4, 6],
                   [8, 10, 12]])

print("\nRow-wise Sum:")
print(np.sum(matrix, axis=1))

print("\nColumn-wise Sum:")
print(np.sum(matrix, axis=0))

"""## Pandas"""

# Import Libraries
import pandas as pd
import seaborn as sns

# ===========================
# Load Titanic Dataset
# ===========================
df = sns.load_dataset("titanic")

# ===========================
# Display Data
# ===========================
print("First 5 Rows:")
print(df.head())

print("\nLast 5 Rows:")
print(df.tail())

print("\nRandom 5 Rows:")
print(df.sample(5))

# ===========================
# Dataset Information
# ===========================
print("\nShape of Dataset:")
print(df.shape)

print("\nNumber of Rows:")
print(df.shape[0])

print("\nNumber of Columns:")
print(df.shape[1])

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

# ===========================
# Statistical Summary
# ===========================
print("\nStatistical Summary:")
print(df.describe())

print("\nSummary Including Categorical Columns:")
print(df.describe(include='all'))

# ===========================
# Missing Values
# ===========================
print("\nMissing Values:")
print(df.isnull().sum())

# ===========================
# Duplicate Values
# ===========================
print("\nDuplicate Rows:")
print(df.duplicated().sum())

# ===========================
# Unique Values
# ===========================
print("\nUnique Values in Each Column:")
print(df.nunique())

print("\nUnique Passenger Classes:")
print(df["class"].unique())

"""## Task 2: Perform data acquisition and exploratory analysis using descriptive statistical measures to understand dataset characteristics (Suggested Dataset: Pima Indians Diabetes Dataset / Iris Dataset)."""

import pandas as pd
from sklearn.datasets import load_iris

# Load Iris dataset from sklearn
iris_raw = load_iris()


iris_df = pd.DataFrame(data=iris_raw.data, columns=iris_raw.feature_names)

# Map numeric targets to taxonomic species names
iris_df['species_id'] = iris_raw.target
species_mapping = {i: name for i, name in enumerate(iris_raw.target_names)}
iris_df['species_name'] = iris_df['species_id'].map(species_mapping)

print("Iris dimensions:", iris_df.shape)
print("Missing entries checking:\n", iris_df.isnull().sum())
print(iris_df.head(3))


# Calculating central tendency across variables
for col in iris_raw.feature_names:
    mean_val = iris_df[col].mean()
    median_val = iris_df[col].median()
    mode_val = iris_df[col].mode()[0]
    print(f"Feature: {col}")
    print(f"  Mean:   {mean_val:.4f} cm")
    print(f"  Median: {median_val:.4f} cm")
    print(f"  Mode:   {mode_val:.4f} cm")
    print("-" * 40)


# Calculating dispersion characteristics
for col in iris_raw.feature_names:
    variance = iris_df[col].var()
    std_dev = iris_df[col].std()
    data_range = iris_df[col].max() - iris_df[col].min()
    q1 = iris_df[col].quantile(0.25)
    q3 = iris_df[col].quantile(0.75)
    print(f"Feature: {col}")
    print(f"  Variance:           {variance:.4f}")
    print(f"  Std Deviation:      {std_dev:.4f}")
    print(f"  Range (Max - Min):  {data_range:.4f}")
    print(f"  IQR (Q3 - Q1):      {q3 - q1:.4f}")
    print("-" * 40)

# Evaluating distribution moments
for col in iris_raw.feature_names:
    skewness = iris_df[col].skew()
    kurtosis = iris_df[col].kurt()
    print(f"Feature: {col}")
    print(f"  Skewness (Asymmetry): {skewness:.4f}")
    print(f"  Kurtosis (Tails):     {kurtosis:.4f}")
    print("-" * 40)

# Segmenting by class species using groupby
grouped_species = iris_df.groupby('species_name')

print("--- Group-Wise Mean Values ---")
print(grouped_species[iris_raw.feature_names].mean())

print("\n--- Group-Wise Standard Deviation Profiles ---")
print(grouped_species[iris_raw.feature_names].std())


aggregated_stats = iris_df.groupby('species_name')['petal length (cm)'].agg(['mean', 'median', 'std', 'skew'])
print("Aggregated Statistics (Petal Length):\n", aggregated_stats)

"""## Task 3: Analyze data distributions and feature relationships using univariate and multivariate visualization techniques (Suggested Dataset: Pima Indians Diabetes Dataset / Iris Dataset)."""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Iris Dataset
df = sns.load_dataset("iris")

# Display first five rows
print(df.head())

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Iris Dataset
df = sns.load_dataset("iris")

# Histogram
plt.figure(figsize=(6,4))
sns.histplot(df["sepal_length"], bins=15, kde=True)
plt.title("24EU02039 Histogram of Sepal Length")
plt.show()

# Count Plot
plt.figure(figsize=(6,4))
sns.countplot(x="species", data=df)
plt.title("24EU02039 Species Count")
plt.show()

# Box Plot
plt.figure(figsize=(6,4))
sns.boxplot(y="petal_length", data=df)
plt.title("24EU02039 Box Plot of Petal Length")
plt.show()

# Violin Plot
plt.figure(figsize=(6,4))
sns.violinplot(y="petal_width", data=df)
plt.title("24EU02039 Violin Plot of Petal Width")
plt.show()

# Density Plot
plt.figure(figsize=(6,4))
sns.kdeplot(df["sepal_width"], fill=True)
plt.title("24EU02039 Density Plot of Sepal Width")
plt.show()

# Scatter Plot
plt.figure(figsize=(6,4))
sns.scatterplot(x="sepal_length", y="petal_length",
                hue="species", data=df)
plt.title("24EU02039 Sepal Length vs Petal Length")
plt.show()

# Pair Plot
sns.pairplot(df, hue="species")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(7,5))
sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap="coolwarm")
plt.title("24EU02039 Correlation Heatmap")
plt.show()

# Box Plot by Species
plt.figure(figsize=(6,4))
sns.boxplot(x="species", y="petal_length", data=df)
plt.title("24EU02039 Petal Length by Species")
plt.show()

# Violin Plot by Species
plt.figure(figsize=(6,4))
sns.violinplot(x="species", y="sepal_width", data=df)
plt.title("24EU02039 Sepal Width by Species")
plt.show()

# Bar Plot
plt.figure(figsize=(6,4))
sns.barplot(x="species", y="petal_width", data=df)
plt.title("24EU02039 Average Petal Width by Species")
plt.show()

"""## Task 4: Interpret statistical insights and identify significant features influencing predictive analysis (Suggested Dataset: Sonar Dataset)."""

import pandas as pd

# Load Sonar Dataset from GitHub
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/sonar.csv"

df = pd.read_csv(url, header=None)

# Rename the last column as Target
df.rename(columns={60: "Target"}, inplace=True)

print(df.head())

## Statistical Insights

# Shape of dataset
print("Shape:", df.shape)

# Data types
print("\nData Types:")
print(df.dtypes)

# Summary statistics
print("\nStatistical Summary:")
print(df.describe())

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Duplicate rows
print("\nDuplicate Rows:")
print(df.duplicated().sum())

# Class distribution
print("\nClass Distribution:")
print(df["Target"].value_counts())

## Correlation Analysi

import matplotlib.pyplot as plt
import seaborn as sns

# Correlation matrix
corr = df.iloc[:, :-1].corr()

plt.figure(figsize=(12,10))
sns.heatmap(corr, cmap="coolwarm")
plt.title("24EU02039 Correlation Matrix")
plt.show()

# identify significant Features

# Correlation of features with Feature 1 (example)
print(df.corr(numeric_only=True)[0].sort_values(ascending=False))

import sys
print(sys.executable)  # Should show ...envs\ML\python.exe
import numpy
print(numpy.__version__)  # Should show 1.26.4

# ==========================================
# Iris Dataset - Basic Exploration
# ==========================================

import pandas as pd
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()

# Convert to DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add target column
df['Species'] = iris.target

# Convert numeric labels to species names
df['Species'] = df['Species'].map({
    0: 'Setosa',
    1: 'Versicolor',
    2: 'Virginica'
})

# Display first 5 rows
print("\n===== First 5 Rows =====")
print(df.head())

# Display last 5 rows
print("\n===== Last 5 Rows =====")
print(df.tail())

# Dataset shape
print("\n===== Dataset Shape =====")
print(df.shape)

# Number of rows and columns
print("\nRows :", df.shape[0])
print("Columns :", df.shape[1])

# Column names
print("\n===== Column Names =====")
print(df.columns.tolist())

# Data types
print("\n===== Data Types =====")
print(df.dtypes)

# Dataset information
print("\n===== Dataset Information =====")
df.info()

# Statistical summary
print("\n===== Statistical Description =====")
print(df.describe())

# Missing values
print("\n===== Missing Values =====")
print(df.isnull().sum())

# Duplicate records
print("\n===== Duplicate Records =====")
print(df.duplicated().sum())

# Random 5 samples
print("\n===== Random 5 Samples =====")
print(df.sample(5))

# Unique values
print("\n===== Unique Values =====")
print(df.nunique())

# Target class distribution
print("\n===== Species Distribution =====")
print(df['Species'].value_counts())

# ==============================================
# Exploratory Data Analysis (EDA) on Titanic Dataset -24EU02039
# ==============================================

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set plot style
sns.set(style="whitegrid")

# ---------------------------------------------
# Create Dataset Manually
# ---------------------------------------------
data = {
    'PassengerId': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Survived': [0, 1, 1, 1, 0, 0, 0, 1, 1, 1],
    'Pclass': [3, 1, 3, 1, 3, 3, 1, 3, 3, 2],
    'Sex': ['male', 'female', 'female', 'female', 'male', 'male', 'male', 'female', 'female', 'female'],
    'Age': [22, 38, 26, 35, 35, 27, 54, 2, 27, 14],
    'Fare': [7.25, 71.2833, 7.925, 53.10, 8.05, 8.4583, 51.8625, 21.075, 11.1333, 30.0708]
}

# Create DataFrame
df = pd.DataFrame(data)

# ---------------------------------------------
# 1. Display Dataset Information
# ---------------------------------------------
print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

# ---------------------------------------------
# 2. Check Missing Values
# ---------------------------------------------
print("\nMissing Values:")
print(df.isnull().sum())

# ---------------------------------------------
# 3. Survival Count Visualization
# ---------------------------------------------
plt.figure(figsize=(6,4))
sns.countplot(x='Survived', data=df)
plt.title("Survival Count -24EU02039")
plt.show()

# ---------------------------------------------
# 4. Age Distribution
# ---------------------------------------------
plt.figure(figsize=(6,4))
sns.histplot(df['Age'], bins=5, kde=True)
plt.title("Age Distribution -24EU02039")
plt.xlabel("Age")
plt.show()

# ---------------------------------------------
# 5. Correlation Heatmap
# ---------------------------------------------
df_corr = df.copy()
df_corr['Sex'] = df_corr['Sex'].map({'male': 0, 'female': 1})

plt.figure(figsize=(8,6))
sns.heatmap(df_corr.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap -24EU02039")
plt.show()

print("\nEDA Completed Successfully!")